[package]
name = "world-simulator"
version = "0.1.0"
edition = "2021"
authors = [
    "Mak K. <mak@makkrnic.info>"
]

[profile.dev]
opt-level = 3

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }
noise = "0.7.0"
ndarray = "0.15.3"
building-blocks = "0.7.1"